# Needed to configure IRSA
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::00000000000:role/my-role

outputs:
  # we limit to sshd logs only
  inputLogTypes: &logTypes
  - sshd
  aws:
    region: "eu-central-1"
    S3:
      enabled: true
      # Needed to import the log types anchor defined above
      inputLogTypes: *logTypes
      bucketName: "my-cluster-logs"
      totalFileSize: "100M"
      s3_object_key_format: "/$TAG/%Y/%m/%d/%H/%M/%S"
