{{- if and .Values.outputs .Values.outputs.inputLogTypes }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.networkPolicy.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  ingress:
  - ports:
    - port: {{ .Values.fluentbit.port }}
      protocol: {{ .Values.fluentbit.protocol }}
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
{{- end }}
