{{- if .Values.fluentbit.customEnabled }}
apiVersion: scheduling.k8s.io/v1
description: High-priority class for fluentbit pods only.
kind: PriorityClass
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ .Values.fluentbit.priorityClass.name }}
preemptionPolicy: PreemptLowerPriority
value: 200000000
{{- end }}
