{{- if not .Values.global.podSecurityStandards.enforced }}
{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
{{- if and .Values.outputs .Values.outputs.inputLogTypes }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.psp.name" . }}
spec:
  privileged: true
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  runAsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - 'secret'
    - 'configMap'
    - 'hostPath'
    - 'projected'
  allowPrivilegeEscalation: true
  hostNetwork: false
  hostIPC: false
  hostPID: false
{{- end }}
{{- end }}
{{- end }}
