{{ if eq (include "resource.vpa.enabled" .) "true" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: fluent-bit
      controlledResources:
        - memory
        - cpu
      maxAllowed:
        memory: 500Mi
      minAllowed:
        memory: 100Mi
        cpu: 200m
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name:  {{ include "resource.default.name"  . }}
  updatePolicy:
    updateMode: Auto
{{ end }}
